service: aws-express-node-ts-quickstart

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  memorySize: 128
  timeout: 6
  versionFunctions: false
  profile: default # use default or custom profile

environment:
  deployment: aws-lambda

functions:
  api:
    handler: dist/aws/router.handler
    events:
      - http:
          path: api/{proxy+}
          #cors: true
          private: false
          method: any